#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running pre-push hook..."

echo "Running migrations and seeders..."
php artisan migrate --env=testing --force
php artisan db:seed --env=testing --force

echo "Running tests..."
./vendor/bin/pest || {
    echo "Tests failed!"
    exit 1
}

echo "✅ Pre-push hook finished successfully!"
